/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author matia
 */
public class AñadirEnfermeraView extends javax.swing.JFrame {

    
    private Menu menuVentana;
    
    public AñadirEnfermeraView() {
        initComponents();
    }
    
    public void setMenuVentana (Menu menuVentana) {
        this.menuVentana = menuVentana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreEnfermeraLabel = new javax.swing.JLabel();
        nombreEnfermeraTextField = new javax.swing.JTextField();
        horarioLabel = new javax.swing.JLabel();
        lunesComboBox = new javax.swing.JComboBox<>();
        martesComboBox = new javax.swing.JComboBox<>();
        miercolesComboBox = new javax.swing.JComboBox<>();
        juevesComboBox = new javax.swing.JComboBox<>();
        viernesComboBox = new javax.swing.JComboBox<>();
        lunesLabel = new javax.swing.JLabel();
        martesLabel = new javax.swing.JLabel();
        miercolesLabel = new javax.swing.JLabel();
        juevesLabel = new javax.swing.JLabel();
        viernesLabel = new javax.swing.JLabel();
        newEnfermeraLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        edadTextField = new javax.swing.JTextField();
        confirmarButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem4 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreEnfermeraLabel.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        nombreEnfermeraLabel.setText("Nombre de la enfermera:");

        nombreEnfermeraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEnfermeraTextFieldActionPerformed(evt);
            }
        });

        horarioLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        horarioLabel.setText("Seleccionar Horarios");

        lunesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        lunesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lunesComboBoxMouseClicked(evt);
            }
        });
        lunesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunesComboBoxActionPerformed(evt);
            }
        });

        martesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        martesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                martesComboBoxMouseClicked(evt);
            }
        });
        martesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martesComboBoxActionPerformed(evt);
            }
        });

        miercolesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        miercolesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miercolesComboBoxMouseClicked(evt);
            }
        });
        miercolesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miercolesComboBoxActionPerformed(evt);
            }
        });

        juevesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        juevesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juevesComboBoxMouseClicked(evt);
            }
        });
        juevesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juevesComboBoxActionPerformed(evt);
            }
        });

        viernesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        viernesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viernesComboBoxMouseClicked(evt);
            }
        });
        viernesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viernesComboBoxActionPerformed(evt);
            }
        });

        lunesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lunesLabel.setText("Lunes");

        martesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        martesLabel.setText("Martes");

        miercolesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        miercolesLabel.setText("Miercoles");

        juevesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        juevesLabel.setText("Jueves");

        viernesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        viernesLabel.setText("Viernes");

        newEnfermeraLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        newEnfermeraLabel.setText("Agregar una nueva Enfermera");

        edadLabel.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        edadLabel.setText("Edad de la enfermera:");

        edadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTextFieldActionPerformed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem4.setText("Exit");
        fileMenu.add(exitMenuItem4);

        MenuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        MenuBar.add(editMenu);

        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edadLabel)
                                    .addComponent(nombreEnfermeraLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreEnfermeraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lunesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lunesLabel))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(martesLabel)
                                    .addComponent(martesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(miercolesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(miercolesLabel))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(juevesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(juevesLabel))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viernesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viernesLabel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(newEnfermeraLabel)))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(horarioLabel)
                        .addGap(334, 334, 334))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(newEnfermeraLabel)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEnfermeraLabel)
                    .addComponent(nombreEnfermeraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadLabel)
                    .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(horarioLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunesLabel)
                    .addComponent(martesLabel)
                    .addComponent(juevesLabel)
                    .addComponent(viernesLabel)
                    .addComponent(miercolesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miercolesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viernesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(martesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juevesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(confirmarButton)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    private void nombreEnfermeraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEnfermeraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEnfermeraTextFieldActionPerformed

    private void lunesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesComboBoxActionPerformed

    private void lunesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lunesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesComboBoxMouseClicked

    private void martesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_martesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_martesComboBoxMouseClicked

    private void martesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_martesComboBoxActionPerformed

    private void miercolesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miercolesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miercolesComboBoxMouseClicked

    private void miercolesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miercolesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miercolesComboBoxActionPerformed

    private void juevesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juevesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_juevesComboBoxMouseClicked

    private void juevesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juevesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juevesComboBoxActionPerformed

    private void viernesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viernesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viernesComboBoxMouseClicked

    private void viernesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viernesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viernesComboBoxActionPerformed

    private void edadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTextFieldActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        menuVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_confirmarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirEnfermeraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirEnfermeraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirEnfermeraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirEnfermeraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirEnfermeraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JTextField edadTextField;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem4;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JComboBox<String> juevesComboBox;
    private javax.swing.JLabel juevesLabel;
    private javax.swing.JComboBox<String> lunesComboBox;
    private javax.swing.JLabel lunesLabel;
    private javax.swing.JComboBox<String> martesComboBox;
    private javax.swing.JLabel martesLabel;
    private javax.swing.JComboBox<String> miercolesComboBox;
    private javax.swing.JLabel miercolesLabel;
    private javax.swing.JLabel newEnfermeraLabel;
    private javax.swing.JLabel nombreEnfermeraLabel;
    private javax.swing.JTextField nombreEnfermeraTextField;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JComboBox<String> viernesComboBox;
    private javax.swing.JLabel viernesLabel;
    // End of variables declaration//GEN-END:variables
}
