/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author matia
 */
public class CambiarTurnos extends javax.swing.JFrame {

    private Menu menuVentana;
    
    public CambiarTurnos() {
        initComponents();
    }
    
    public void setMenuVentana (Menu menuVentana) {
        this.menuVentana = menuVentana;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiarTurnoEnfermeraLabel = new javax.swing.JLabel();
        martesLabel = new javax.swing.JLabel();
        miercolesLabel = new javax.swing.JLabel();
        juevesLabel = new javax.swing.JLabel();
        viernesLabel = new javax.swing.JLabel();
        nombreEnfermeraLabel = new javax.swing.JLabel();
        nombreEnfermeraTextField = new javax.swing.JTextField();
        horarioLabel = new javax.swing.JLabel();
        lunesComboBox = new javax.swing.JComboBox<>();
        martesComboBox = new javax.swing.JComboBox<>();
        miercolesComboBox = new javax.swing.JComboBox<>();
        juevesComboBox = new javax.swing.JComboBox<>();
        viernesComboBox = new javax.swing.JComboBox<>();
        lunesLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem4 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cambiarTurnoEnfermeraLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        cambiarTurnoEnfermeraLabel.setText("Cambiar turnos a una Enfermera");

        martesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        martesLabel.setText("Martes");

        miercolesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        miercolesLabel.setText("Miercoles");

        juevesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        juevesLabel.setText("Jueves");

        viernesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        viernesLabel.setText("Viernes");

        nombreEnfermeraLabel.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        nombreEnfermeraLabel.setText("Nombre de la enfermera:");

        nombreEnfermeraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEnfermeraTextFieldActionPerformed(evt);
            }
        });

        horarioLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        horarioLabel.setText("Seleccionar nuevos horarios");

        lunesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        lunesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lunesComboBoxMouseClicked(evt);
            }
        });
        lunesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunesComboBoxActionPerformed(evt);
            }
        });

        martesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        martesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                martesComboBoxMouseClicked(evt);
            }
        });
        martesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martesComboBoxActionPerformed(evt);
            }
        });

        miercolesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        miercolesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miercolesComboBoxMouseClicked(evt);
            }
        });
        miercolesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miercolesComboBoxActionPerformed(evt);
            }
        });

        juevesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        juevesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juevesComboBoxMouseClicked(evt);
            }
        });
        juevesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juevesComboBoxActionPerformed(evt);
            }
        });

        viernesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche", "Libre" }));
        viernesComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viernesComboBoxMouseClicked(evt);
            }
        });
        viernesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viernesComboBoxActionPerformed(evt);
            }
        });

        lunesLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lunesLabel.setText("Lunes");

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem4.setText("Exit");
        fileMenu.add(exitMenuItem4);

        MenuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        MenuBar.add(editMenu);

        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(cambiarTurnoEnfermeraLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lunesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lunesLabel))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(martesLabel)
                                    .addComponent(martesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(miercolesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(miercolesLabel))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(juevesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(juevesLabel))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viernesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viernesLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(horarioLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreEnfermeraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreEnfermeraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(cambiarTurnoEnfermeraLabel)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEnfermeraLabel)
                    .addComponent(nombreEnfermeraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(horarioLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunesLabel)
                    .addComponent(martesLabel)
                    .addComponent(juevesLabel)
                    .addComponent(viernesLabel)
                    .addComponent(miercolesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miercolesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viernesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(martesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juevesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(confirmarButton)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEnfermeraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEnfermeraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEnfermeraTextFieldActionPerformed

    private void lunesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lunesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesComboBoxMouseClicked

    private void lunesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesComboBoxActionPerformed

    private void martesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_martesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_martesComboBoxMouseClicked

    private void martesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_martesComboBoxActionPerformed

    private void miercolesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miercolesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miercolesComboBoxMouseClicked

    private void miercolesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miercolesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miercolesComboBoxActionPerformed

    private void juevesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juevesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_juevesComboBoxMouseClicked

    private void juevesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juevesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juevesComboBoxActionPerformed

    private void viernesComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viernesComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viernesComboBoxMouseClicked

    private void viernesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viernesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viernesComboBoxActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        menuVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarTurnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel cambiarTurnoEnfermeraLabel;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem4;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JComboBox<String> juevesComboBox;
    private javax.swing.JLabel juevesLabel;
    private javax.swing.JComboBox<String> lunesComboBox;
    private javax.swing.JLabel lunesLabel;
    private javax.swing.JComboBox<String> martesComboBox;
    private javax.swing.JLabel martesLabel;
    private javax.swing.JComboBox<String> miercolesComboBox;
    private javax.swing.JLabel miercolesLabel;
    private javax.swing.JLabel nombreEnfermeraLabel;
    private javax.swing.JTextField nombreEnfermeraTextField;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JComboBox<String> viernesComboBox;
    private javax.swing.JLabel viernesLabel;
    // End of variables declaration//GEN-END:variables
}
