/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author matia
 */
public class Menu extends javax.swing.JFrame {

 
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newEnfermeraLabel = new javax.swing.JLabel();
        añadirEnfermeraButton = new javax.swing.JButton();
        cambiarTurnosButton = new javax.swing.JButton();
        eliminarEnfermeraButton = new javax.swing.JButton();
        buscarEnfermeraButton = new javax.swing.JButton();
        buscarDiaButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem4 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(getIconImages());
        setName("Menu"); // NOI18N
        setSize(new java.awt.Dimension(850, 547));

        newEnfermeraLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        newEnfermeraLabel.setText("Menu");

        añadirEnfermeraButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        añadirEnfermeraButton.setText("Agregar una nueva Enfermera");
        añadirEnfermeraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirEnfermeraButtonActionPerformed(evt);
            }
        });

        cambiarTurnosButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cambiarTurnosButton.setText("Cambiar turnos a una Enfermera");
        cambiarTurnosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTurnosButtonActionPerformed(evt);
            }
        });

        eliminarEnfermeraButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        eliminarEnfermeraButton.setText("Eliminar una Enfermera");
        eliminarEnfermeraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEnfermeraButtonActionPerformed(evt);
            }
        });

        buscarEnfermeraButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buscarEnfermeraButton.setText("Buscar Enfermera");
        buscarEnfermeraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEnfermeraButtonActionPerformed(evt);
            }
        });

        buscarDiaButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buscarDiaButton.setText("Buscar dia con los horarios");
        buscarDiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDiaButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem4.setText("Exit");
        exitMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem4);

        MenuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        MenuBar.add(editMenu);

        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(newEnfermeraLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buscarDiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarEnfermeraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eliminarEnfermeraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cambiarTurnosButton)
                        .addComponent(añadirEnfermeraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(newEnfermeraLabel)
                .addGap(41, 41, 41)
                .addComponent(añadirEnfermeraButton)
                .addGap(28, 28, 28)
                .addComponent(cambiarTurnosButton)
                .addGap(30, 30, 30)
                .addComponent(eliminarEnfermeraButton)
                .addGap(30, 30, 30)
                .addComponent(buscarEnfermeraButton)
                .addGap(30, 30, 30)
                .addComponent(buscarDiaButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    private void añadirEnfermeraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirEnfermeraButtonActionPerformed
        AñadirEnfermeraView añadirEnfermeraVentana = new AñadirEnfermeraView();
        añadirEnfermeraVentana.setMenuVentana(this);
        añadirEnfermeraVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_añadirEnfermeraButtonActionPerformed

    private void cambiarTurnosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTurnosButtonActionPerformed
        CambiarTurnos cambiarTurnosVentana = new CambiarTurnos();
        cambiarTurnosVentana.setMenuVentana(this);
        cambiarTurnosVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cambiarTurnosButtonActionPerformed

    private void eliminarEnfermeraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEnfermeraButtonActionPerformed
        EliminarEnfermera eliminarVentana = new EliminarEnfermera();
        eliminarVentana.setMenuVentana(this);
        eliminarVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarEnfermeraButtonActionPerformed

    private void buscarEnfermeraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEnfermeraButtonActionPerformed
        BuscarEnfermera buscarVentana = new BuscarEnfermera();
        buscarVentana.setMenuVentana(this);
        buscarVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buscarEnfermeraButtonActionPerformed

    private void buscarDiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDiaButtonActionPerformed
        BuscarDia buscarDiaVentana = new BuscarDia();
        buscarDiaVentana.setMenuVentana(this);
        buscarDiaVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buscarDiaButtonActionPerformed

    private void exitMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton añadirEnfermeraButton;
    private javax.swing.JButton buscarDiaButton;
    private javax.swing.JButton buscarEnfermeraButton;
    private javax.swing.JButton cambiarTurnosButton;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton eliminarEnfermeraButton;
    private javax.swing.JMenuItem exitMenuItem4;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel newEnfermeraLabel;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
}
